// Generated by scripts/build-maps.mjs. Positions are percentages of the map image box.

export const ITALY_MAP = { width: 600, height: 700 } as const;
export const EUROPE_MAP = { width: 800, height: 720 } as const;

export const italyPins = {
  "milan": {
    "x": 22.3,
    "y": 17.1
  },
  "dolomites": {
    "x": 44.2,
    "y": 7.1
  },
  "venice": {
    "x": 48.1,
    "y": 17.3
  },
  "florence": {
    "x": 38,
    "y": 35.5
  },
  "rome": {
    "x": 49.5,
    "y": 51.9
  },
  "amalfi": {
    "x": 66.8,
    "y": 63.8
  }
} as const;

export const europePins = {
  "amsterdam": {
    "x": 39.2,
    "y": 47.9
  },
  "paris": {
    "x": 34.3,
    "y": 59.8
  },
  "london": {
    "x": 29.5,
    "y": 50.9
  },
  "germany": {
    "x": 49.9,
    "y": 52
  },
  "barcelona": {
    "x": 33.9,
    "y": 82.5
  },
  "switzerland": {
    "x": 45.6,
    "y": 66.3
  },
  "greece": {
    "x": 73.2,
    "y": 87.9
  },
  "italy": {
    "x": 54.4,
    "y": 79
  }
} as const;
