// Generates the Italy + Europe outline SVGs and the projected pin positions used by the map sections.
// Usage: node scripts/build-maps.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { geoMercator, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const require = createRequire(import.meta.url);
const topo = JSON.parse(readFileSync(require.resolve("world-atlas/countries-50m.json"), "utf8"));
const countries = feature(topo, topo.objects.countries).features;

const EUROPE = new Set([
  "Albania", "Austria", "Belarus", "Belgium", "Bosnia and Herz.", "Bulgaria", "Croatia",
  "Czechia", "Denmark", "Estonia", "Finland", "France", "Germany", "Greece", "Hungary",
  "Ireland", "Italy", "Kosovo", "Latvia", "Liechtenstein", "Lithuania", "Luxembourg",
  "Macedonia", "Moldova", "Montenegro", "Netherlands", "Norway", "Poland", "Portugal",
  "Romania", "San Marino", "Serbia", "Slovakia", "Slovenia", "Spain", "Sweden", "Switzerland",
  "Ukraine", "United Kingdom", "Andorra", "Monaco", "Vatican", "Malta", "Cyprus",
]);

const round = (n) => Math.round(n * 10) / 10;
const pct = (n, total) => Math.round((n / total) * 1000) / 10;

function pins(projection, width, height, places) {
  return Object.fromEntries(
    Object.entries(places).map(([key, lonLat]) => {
      const [x, y] = projection(lonLat);
      return [key, { x: pct(x, width), y: pct(y, height) }];
    })
  );
}

// Italy: solid silhouette.
const italy = countries.find((c) => c.properties.name === "Italy");
const IW = 600;
const IH = 700;
const italyProjection = geoMercator().fitExtent([[4, 4], [IW - 4, IH - 4]], italy);
const italyPath = geoPath(italyProjection).digits(1)(italy);
writeFileSync(
  "public/assets/web/map-italy.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${IW} ${IH}"><path fill="#dfd9c9" d="${italyPath}"/></svg>\n`
);

// Europe: outlined country borders, clipped to a frame around western/central Europe.
const EW = 800;
const EH = 720;
const frame = {
  type: "MultiPoint",
  coordinates: [[-11, 35], [32, 35], [32, 64], [-11, 64]],
};
const europeProjection = geoMercator()
  .fitExtent([[0, 0], [EW, EH]], frame)
  .clipExtent([[0, 0], [EW, EH]]);
const europePath = geoPath(europeProjection).digits(1);
const europePaths = countries
  .filter((c) => EUROPE.has(c.properties.name))
  .map((c) => `<path d="${europePath(c)}"/>`)
  .join("");
writeFileSync(
  "public/assets/web/map-europe.svg",
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${EW} ${EH}"><g fill="none" stroke="#482117" stroke-width="1.6" stroke-linejoin="round">${europePaths}</g></svg>\n`
);

const italyPins = pins(italyProjection, IW, IH, {
  milan: [9.19, 45.46],
  dolomites: [11.85, 46.45],
  venice: [12.33, 45.44],
  florence: [11.1, 43.6],
  rome: [12.5, 41.9],
  amalfi: [14.6, 40.63],
});
const europePins = pins(europeProjection, EW, EH, {
  amsterdam: [4.9, 52.37],
  paris: [2.35, 48.86],
  london: [-0.13, 51.51],
  germany: [10.45, 51.17],
  barcelona: [2.17, 41.39],
  switzerland: [8.23, 46.82],
  greece: [22.5, 39.5],
  italy: [12.8, 42.6],
});

writeFileSync(
  "app/data/map-pins.ts",
  `// Generated by scripts/build-maps.mjs. Positions are percentages of the map image box.\n\n` +
    `export const ITALY_MAP = { width: ${IW}, height: ${IH} } as const;\n` +
    `export const EUROPE_MAP = { width: ${EW}, height: ${EH} } as const;\n\n` +
    `export const italyPins = ${JSON.stringify(italyPins, null, 2)} as const;\n\n` +
    `export const europePins = ${JSON.stringify(europePins, null, 2)} as const;\n`
);

console.log("italy", round(italyPath.length / 1024), "KB path");
console.log("italy pins", italyPins);
console.log("europe pins", europePins);
